// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYMJedGuXdiJU-EeTeqD8SwbQp90X15P0',
    appId: '1:619445260311:web:921601aca66bd7b5658c52',
    messagingSenderId: '619445260311',
    projectId: 'ecommerceapp-83b39',
    authDomain: 'ecommerceapp-83b39.firebaseapp.com',
    storageBucket: 'ecommerceapp-83b39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdSXrHPXaKeOnV89UFdI_M1JyYjkkUlbg',
    appId: '1:619445260311:android:eae9d81df388d7c0658c52',
    messagingSenderId: '619445260311',
    projectId: 'ecommerceapp-83b39',
    storageBucket: 'ecommerceapp-83b39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDghoMUjJMGEQLC2hPACF_zDuZbqkLBTts',
    appId: '1:619445260311:ios:eb724251873fd04e658c52',
    messagingSenderId: '619445260311',
    projectId: 'ecommerceapp-83b39',
    storageBucket: 'ecommerceapp-83b39.appspot.com',
    androidClientId: '619445260311-o8uf5aa7htukb9runosp89jbtmpmncl5.apps.googleusercontent.com',
    iosClientId: '619445260311-7609otvpecb0e51qkioeot3gaak40v96.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDghoMUjJMGEQLC2hPACF_zDuZbqkLBTts',
    appId: '1:619445260311:ios:eb724251873fd04e658c52',
    messagingSenderId: '619445260311',
    projectId: 'ecommerceapp-83b39',
    storageBucket: 'ecommerceapp-83b39.appspot.com',
    androidClientId: '619445260311-o8uf5aa7htukb9runosp89jbtmpmncl5.apps.googleusercontent.com',
    iosClientId: '619445260311-7609otvpecb0e51qkioeot3gaak40v96.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYMJedGuXdiJU-EeTeqD8SwbQp90X15P0',
    appId: '1:619445260311:web:82b947963daf7b78658c52',
    messagingSenderId: '619445260311',
    projectId: 'ecommerceapp-83b39',
    authDomain: 'ecommerceapp-83b39.firebaseapp.com',
    storageBucket: 'ecommerceapp-83b39.appspot.com',
  );

}